//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.14 at 06:17:50 PM ICT 
//


package thuyvtk.jaxbObject;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for houseItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="houseItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="linkNew" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="timePost" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="img" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rentAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="size" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="toilet" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="people" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="electricPrice" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="waterPrice" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bonus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rentPrice" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="detail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "houseItem", propOrder = {
    "id",
    "title",
    "linkNew",
    "timePost",
    "img",
    "rentAddress",
    "size",
    "toilet",
    "people",
    "electricPrice",
    "waterPrice",
    "bonus",
    "rentPrice",
    "detail",
    "latitude",
    "longitude"
})
public class HouseItem {

    @XmlElement(required = true)
    protected BigInteger id;
    @XmlElement(required = true)
    protected String title;
    @XmlElement(required = true)
    protected String linkNew;
    @XmlElement(required = true)
    protected String timePost;
    @XmlElement(required = true)
    protected String img;
    @XmlElement(required = true)
    protected String rentAddress;
    @XmlElement(required = true)
    protected String size;
    @XmlElement(required = true)
    protected String toilet;
    @XmlElement(required = true)
    protected String people;
    @XmlElement(required = true)
    protected String electricPrice;
    @XmlElement(required = true)
    protected String waterPrice;
    @XmlElement(required = true)
    protected String bonus;
    @XmlElement(required = true)
    protected BigInteger rentPrice;
    @XmlElement(required = true)
    protected String detail;
    @XmlElement(required = true)
    protected BigDecimal latitude;
    @XmlElement(required = true)
    protected BigDecimal longitude;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the linkNew property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkNew() {
        return linkNew;
    }

    /**
     * Sets the value of the linkNew property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkNew(String value) {
        this.linkNew = value;
    }

    /**
     * Gets the value of the timePost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimePost() {
        return timePost;
    }

    /**
     * Sets the value of the timePost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimePost(String value) {
        this.timePost = value;
    }

    /**
     * Gets the value of the img property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImg() {
        return img;
    }

    /**
     * Sets the value of the img property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImg(String value) {
        this.img = value;
    }

    /**
     * Gets the value of the rentAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRentAddress() {
        return rentAddress;
    }

    /**
     * Sets the value of the rentAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRentAddress(String value) {
        this.rentAddress = value;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSize(String value) {
        this.size = value;
    }

    /**
     * Gets the value of the toilet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToilet() {
        return toilet;
    }

    /**
     * Sets the value of the toilet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToilet(String value) {
        this.toilet = value;
    }

    /**
     * Gets the value of the people property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeople() {
        return people;
    }

    /**
     * Sets the value of the people property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeople(String value) {
        this.people = value;
    }

    /**
     * Gets the value of the electricPrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElectricPrice() {
        return electricPrice;
    }

    /**
     * Sets the value of the electricPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElectricPrice(String value) {
        this.electricPrice = value;
    }

    /**
     * Gets the value of the waterPrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWaterPrice() {
        return waterPrice;
    }

    /**
     * Sets the value of the waterPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWaterPrice(String value) {
        this.waterPrice = value;
    }

    /**
     * Gets the value of the bonus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBonus() {
        return bonus;
    }

    /**
     * Sets the value of the bonus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBonus(String value) {
        this.bonus = value;
    }

    /**
     * Gets the value of the rentPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRentPrice() {
        return rentPrice;
    }

    /**
     * Sets the value of the rentPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRentPrice(BigInteger value) {
        this.rentPrice = value;
    }

    /**
     * Gets the value of the detail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDetail() {
        return detail;
    }

    /**
     * Sets the value of the detail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDetail(String value) {
        this.detail = value;
    }

    /**
     * Gets the value of the latitude property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLatitude() {
        return latitude;
    }

    /**
     * Sets the value of the latitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLatitude(BigDecimal value) {
        this.latitude = value;
    }

    /**
     * Gets the value of the longitude property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     * Sets the value of the longitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLongitude(BigDecimal value) {
        this.longitude = value;
    }

}
