//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.14 at 06:17:50 PM ICT 
//


package thuyvtk.jaxbObject;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the thuyvtk.jaxbObject package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Houses_QNAME = new QName("thuyvtk.xsd", "houses");
    private final static QName _Markets_QNAME = new QName("thuyvtk.xsd", "markets");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: thuyvtk.jaxbObject
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ListHouse }
     * 
     */
    public ListHouse createListHouse() {
        return new ListHouse();
    }

    /**
     * Create an instance of {@link HouseItem }
     * 
     */
    public HouseItem createHouseItem() {
        return new HouseItem();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListHouse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "thuyvtk.xsd", name = "houses")
    public JAXBElement<ListHouse> createHouses(ListHouse value) {
        return new JAXBElement<ListHouse>(_Houses_QNAME, ListHouse.class, null, value);
    }
    
    /**
     * Create an instance of {@link ListMarkets }
     * 
     */
    public ListMarkets createListMarkets() {
        return new ListMarkets();
    }

    /**
     * Create an instance of {@link MarketItem }
     * 
     */
    public MarketItem createMarketItem() {
        return new MarketItem();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListMarkets }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "thuyvtk.xsd", name = "markets")
    public JAXBElement<ListMarkets> createMarkets(ListMarkets value) {
        return new JAXBElement<ListMarkets>(_Markets_QNAME, ListMarkets.class, null, value);
    }

}
